py37:
  image: python:3.7
  script:
  - python setup.py install
  - python -m unittest discover -s tests/ -p 'test*.py'

py36:
  image: python:3.6
  script:
  - python setup.py install
  - python -m unittest discover -s tests/ -p 'test*.py'
